[package]
name = "testserver"
version = "0.1.0"
authors = ["ryanbreaux"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.4"
listenfd = "0.3"